/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kafka.client.examples3;

import static org.junit.Assert.assertTrue;


import org.junit.Test;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
