/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cybear.jms;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MessageStoreTest {
    @Test void someLibraryMethodReturnsTrue() {        
        assertTrue(MessageStore.getInstance().someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
